# Generated by Django 5.1.1 on 2024-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='livre_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='membre_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
