# Generated by Django 5.1.1 on 2024-11-08 15:36

import django.core.validators
import testdb.models.book
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='livre_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='membre_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Image de couverture', null=True, upload_to='book_covers/', validators=[testdb.models.book.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Prix du livre', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
