# Generated by Django 5.1.1 on 2024-10-23 14:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description du livre', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix du livre', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cover_image', models.ImageField(blank=True, help_text='Image de couverture', null=True, upload_to='book_covers/')),
                ('total_copies', models.PositiveIntegerField(help_text="Nombre total d'exemplaires", validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.PositiveIntegerField(help_text="Nombre d'exemplaires disponibles", validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('is_staff', models.BooleanField(blank=True, default=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('is_superuser', models.BooleanField(default=True, null=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('rendu', models.BooleanField(default=False)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.book')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
