# Generated by Django 5.1.1 on 2024-10-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='date_de_retour',
        ),
    ]
