# Generated by Django 5.1.1 on 2024-10-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_emprunt_livre_titre_emprunt_membre_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='copies_restantes',
            field=models.IntegerField(default=0),
        ),
    ]
