# Generated by Django 5.1.1 on 2024-12-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_alter_book_cover_image_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Fichier PDF du livre', null=True, upload_to='book_pdfs/'),
        ),
    ]
