# Generated by Django 5.1.1 on 2024-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
