# Generated by Django 5.1.1 on 2024-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
