# Generated by Django 5.1.1 on 2024-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0010_customuser_is_admin_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
