# Generated by Django 5.1.1 on 2024-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0013_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
